import type { IndustryConfig } from '../types';

export const INDUSTRIES: Record<string, IndustryConfig> = {
  barber: {
    id: 'barber',
    label: 'Barber',
    businessName: 'Montage Cuts',
    tagline: 'Sharp fades, straight razor finishes, no-fuss bookings.',
    accent: 'var(--cyan)',
    address: '14 High St, Fictional Springs',
    reviewScore: 4.8,
    reviewCount: 96,
    services: ['Skin Fade', 'Beard Trim', 'Hot Towel Shave', 'Kids Cut'],
    missedCallText: 'Missed call from 0412 333 ••• — caller did not leave a voicemail.',
    instantSmsIntro:
      "Hey! Sorry we missed your call at Montage Cuts. What can we help with today?",
    avgJobValue: 45,
    enquiryOptions: [
      {
        id: 'book',
        label: 'Book appointment',
        need: 'New booking for a skin fade',
        urgency: 'Medium',
        estValue: 45,
        nextAction: 'Offer next available slot and confirm by SMS',
        smsReply: "Easy! Our next open chair is Thurs 2:30pm or Fri 10am — which suits?",
        playbook: [
          'Confirm preferred barber if customer has one',
          'Offer two real time slots, not a generic "call us back"',
          'Send a calendar confirmation SMS immediately',
          'Add a reminder 2 hours before appointment',
        ],
      },
      {
        id: 'change',
        label: 'Change appointment',
        need: 'Reschedule an existing booking',
        urgency: 'Low',
        estValue: 45,
        nextAction: 'Pull existing booking and offer alternative times',
        smsReply: "No problem — what day works better for you? We'll move it across.",
        playbook: [
          'Look up the existing booking by phone number',
          'Offer 2-3 alternative slots same week',
          'Confirm change in writing via SMS',
          'Cancel the old slot so it is not double-held',
        ],
      },
      {
        id: 'walkin',
        label: 'Walk-in today',
        need: 'Same-day walk-in availability',
        urgency: 'High',
        estValue: 45,
        nextAction: 'Check live chair availability and reply with wait time',
        smsReply: "We've got a chair free in about 20 mins if you can swing by!",
        playbook: [
          'Check current queue / chair status',
          'Reply with an honest wait-time estimate',
          'Hold the slot for 15 minutes only',
          'Offer to text when a chair frees up if currently full',
        ],
      },
      {
        id: 'prices',
        label: 'Prices',
        need: 'Pricing enquiry',
        urgency: 'Low',
        estValue: 45,
        nextAction: 'Send price list and invite booking',
        smsReply: "Skin fade is $45, beard trim $20, combo $58. Want me to lock in a time?",
        playbook: [
          'Send clear price list, no surprises later',
          'Mention any current promo or loyalty offer',
          'Invite them straight into a booking slot',
        ],
      },
      {
        id: 'urgent',
        label: 'Urgent callback',
        need: 'Customer requesting urgent callback',
        urgency: 'Urgent',
        estValue: 45,
        nextAction: 'Flag to staff for callback within 15 minutes',
        smsReply: "Got it — flagging this as urgent, one of the team will call you back shortly.",
        playbook: [
          'Flag enquiry as urgent in the team channel',
          'Assign to whichever staff member is free first',
          'Call back within an agreed time window',
          'Log outcome so nothing falls through the cracks',
        ],
      },
    ],
    followUp: {
      product: 'Frother',
      headline: 'Frother — bring them back before they forget you',
      message: "Looking sharp! Your usual fade is due in ~3 weeks. Want us to pencil it in?",
      explain: 'Frother brings customers back with a friendly, well-timed nudge — no nagging, just good timing.',
    },
  },

  builder: {
    id: 'builder',
    label: 'Builder',
    businessName: 'Montage Build Co.',
    tagline: 'Renovations, extensions and repairs done properly.',
    accent: '#E08A2E',
    address: '7 Trade Cres, Fictional Springs',
    reviewScore: 4.9,
    reviewCount: 64,
    services: ['Kitchen Renovations', 'Extensions', 'Decks & Pergolas', 'General Repairs'],
    missedCallText: 'Missed call from 0488 271 ••• — caller did not leave a voicemail.',
    instantSmsIntro:
      "Hi, sorry we missed your call at Montage Build Co. What's the job you're after a hand with?",
    avgJobValue: 8500,
    enquiryOptions: [
      {
        id: 'quote',
        label: 'Request quote',
        need: 'Quote request for a renovation job',
        urgency: 'Medium',
        estValue: 8500,
        nextAction: 'Book a site measure / send quote questionnaire',
        smsReply: "Keen to help — can you send a couple of photos and we'll line up a site visit?",
        playbook: [
          'Ask for photos and rough scope by text',
          'Qualify budget range early, politely',
          'Book a site visit within 48 hours',
          'Send written quote within agreed timeframe',
        ],
      },
      {
        id: 'existing',
        label: 'Existing project',
        need: 'Update request on a current job',
        urgency: 'Medium',
        estValue: 8500,
        nextAction: 'Route to site supervisor for status update',
        smsReply: "On it — I'll get the site supervisor to send you a progress update today.",
        playbook: [
          'Identify which job/site the enquiry relates to',
          'Route to the supervisor running that job',
          'Reply with a timeline, not just "soon"',
          'Log the update in the job file',
        ],
      },
      {
        id: 'repair',
        label: 'Repair job',
        need: 'Smaller repair or fix-up enquiry',
        urgency: 'High',
        estValue: 1200,
        nextAction: 'Schedule a tradesperson within the week',
        smsReply: "We can usually get a repair like that scheduled within the week — can you describe the issue?",
        playbook: [
          'Get a short description and photo if possible',
          'Estimate rough cost band before site visit',
          'Schedule within the week for smaller jobs',
        ],
      },
      {
        id: 'supplier',
        label: 'Supplier/subcontractor enquiry',
        need: 'Trade or supplier wanting to connect',
        urgency: 'Low',
        estValue: 0,
        nextAction: 'Forward to procurement / office manager',
        smsReply: "Thanks for reaching out — I'll pass your details to our office manager.",
        playbook: [
          'Confirm what trade/supply category they cover',
          'Forward details to office manager, not site staff',
          'No action required from on-site crew',
        ],
      },
    ],
    followUp: {
      product: 'Ripple',
      headline: 'Ripple — turn a finished job into your next lead',
      message: "Hope the new deck is treating you well! Mind leaving us a quick review? It really helps other locals find us.",
      explain: 'Ripple follows up for reviews and referrals once the job is done — compounding word-of-mouth automatically.',
    },
  },

  electrician: {
    id: 'electrician',
    label: 'Electrician',
    businessName: 'Montage Electrical',
    tagline: 'Licensed sparkies for homes and small business.',
    accent: '#F5C800',
    address: '22 Volt Ave, Fictional Springs',
    reviewScore: 4.9,
    reviewCount: 81,
    services: ['Switchboard Upgrades', 'Fault Finding', 'Lighting Installs', 'Safety Inspections'],
    missedCallText: 'Missed call from 0433 902 ••• — caller did not leave a voicemail.',
    instantSmsIntro:
      "Hi, sorry we missed your call at Montage Electrical. Is this urgent or can it wait for a booked visit?",
    avgJobValue: 650,
    enquiryOptions: [
      {
        id: 'fault',
        label: 'Urgent electrical fault',
        need: 'Active fault — power loss, sparking, burning smell',
        urgency: 'Urgent',
        estValue: 650,
        nextAction: 'Escalate to on-call electrician immediately',
        smsReply: "If you smell burning or see sparks, switch off at the board and stay clear — we're calling you back right now.",
        playbook: [
          'Advise customer to isolate power at the switchboard if safe to do so',
          'Escalate immediately to the on-call electrician',
          'This is a demo workflow only — not a substitute for emergency services or certified safety advice',
          'Confirm arrival window as soon as a tech is assigned',
        ],
      },
      {
        id: 'quote',
        label: 'Request quote',
        need: 'Quote for switchboard or installation work',
        urgency: 'Medium',
        estValue: 650,
        nextAction: 'Book a quoting visit',
        smsReply: "Happy to quote that — can you tell us a bit more about the job and we'll get a time locked in?",
        playbook: [
          'Get a written description of the job scope',
          'Check if a site visit is needed before quoting',
          'Book within a few business days',
        ],
      },
      {
        id: 'existing',
        label: 'Existing booking',
        need: 'Question about an already-booked job',
        urgency: 'Low',
        estValue: 650,
        nextAction: 'Confirm booking details via SMS',
        smsReply: "Let me check that booking for you — confirming your appointment details now.",
        playbook: [
          'Look up booking by name or phone number',
          'Confirm date, time and scope back to customer',
          'Update booking if anything has changed',
        ],
      },
      {
        id: 'general',
        label: 'General question',
        need: 'General enquiry, not urgent',
        urgency: 'Low',
        estValue: 0,
        nextAction: 'Answer directly or forward to office',
        smsReply: "Good question — let me get you a proper answer and come back to you shortly.",
        playbook: [
          'Answer simple questions directly where possible',
          'Forward anything technical to a licensed electrician',
          'Avoid giving specific safety or compliance advice over text',
        ],
      },
    ],
    followUp: {
      product: 'Ripple',
      headline: 'Ripple — ask at the right moment',
      message: "Glad we could sort that fault out! If you have 30 seconds, a quick review helps other locals find a sparky they can trust.",
      explain: 'Ripple times the review and referral ask for right after the job is done, when satisfaction is highest.',
    },
  },

  cafe: {
    id: 'cafe',
    label: 'Cafe',
    businessName: 'Montage Coffee',
    tagline: 'Locally roasted coffee and all-day breakfast.',
    accent: 'var(--green)',
    address: '3 Brew Lane, Fictional Springs',
    reviewScore: 4.7,
    reviewCount: 212,
    services: ['Breakfast Menu', 'Specialty Coffee', 'Catering Trays', 'Function Bookings'],
    missedCallText: 'Missed call from 0401 558 ••• — caller did not leave a voicemail.',
    instantSmsIntro:
      "Hi! Sorry we missed your call at Montage Coffee. What can we sort out for you?",
    avgJobValue: 65,
    enquiryOptions: [
      {
        id: 'table',
        label: 'Table booking',
        need: 'Table reservation enquiry',
        urgency: 'Low',
        estValue: 65,
        nextAction: 'Confirm table booking by SMS',
        smsReply: "Sure thing — how many people and what time were you after?",
        playbook: [
          'Confirm party size, date and time',
          'Check seating availability before confirming',
          'Send confirmation SMS with the booking details',
        ],
      },
      {
        id: 'catering',
        label: 'Catering enquiry',
        need: 'Catering order for an event',
        urgency: 'Medium',
        estValue: 350,
        nextAction: 'Send catering menu and confirm headcount',
        smsReply: "We'd love to cater that — roughly how many people and what date?",
        playbook: [
          'Get headcount, date and dietary requirements',
          'Send catering menu and price guide',
          'Confirm order at least 48 hours ahead',
        ],
      },
      {
        id: 'function',
        label: 'Function enquiry',
        need: 'Venue/function space enquiry',
        urgency: 'Medium',
        estValue: 600,
        nextAction: 'Check function space availability',
        smsReply: "We can definitely look at hosting that — what date and roughly how many guests?",
        playbook: [
          'Check function space availability for the date',
          'Clarify guest numbers and any special requests',
          'Send a simple function package outline',
        ],
      },
      {
        id: 'largeorder',
        label: 'Large order',
        need: 'Large takeaway / office order',
        urgency: 'High',
        estValue: 180,
        nextAction: 'Confirm pickup time and prep the order',
        smsReply: "No worries — what time do you need it ready for pickup?",
        playbook: [
          'Confirm exact order and pickup time',
          'Flag to kitchen staff with enough lead time',
          'Text when the order is ready',
        ],
      },
      {
        id: 'general',
        label: 'General question',
        need: 'General enquiry about the cafe',
        urgency: 'Low',
        estValue: 0,
        nextAction: 'Answer directly via SMS',
        smsReply: "Happy to help — what would you like to know?",
        playbook: [
          'Answer hours, menu or location questions directly',
          'Forward anything unusual to the manager on shift',
        ],
      },
    ],
    followUp: {
      product: 'Frother',
      headline: 'Frother — turn first-timers into regulars',
      message: "Thanks for stopping in! Your loyalty card has 1 stamp — 9 more for a free coffee on the house.",
      explain: 'Frother nudges customers back with loyalty and return-visit prompts, timed automatically.',
    },
  },
};

export const INDUSTRY_LIST = Object.values(INDUSTRIES);
